"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";
import * as tus from "tus-js-client";
import { CheckCircle2, Pause, Play, RefreshCcw, UploadCloud, X } from "lucide-react";
import type { MediaResourceType } from "../../lib/bunny/types";

type UploadedAsset = { id: string; resourceType: string; provider: string; publicUrl?: string | null; thumbnailUrl?: string | null; embedUrl?: string | null; processingStatus: string };
type Props = { resourceType: MediaResourceType; academyId?: string; courseId?: string; lessonId?: string; acceptedMimeTypes?: string[]; maximumFileSize?: number; multiple?: boolean; aspectRatio?: number; onUploadComplete?: (asset: UploadedAsset) => void; onUploadError?: (message: string) => void };
type Phase = "idle" | "ready" | "uploading" | "paused" | "processing" | "success" | "error" | "cancelled";
const phoneImageTypes=["image/jpeg","image/png","image/webp","image/avif","image/heic","image/heif"];const defaults: Record<MediaResourceType, string[]> = { video:["video/mp4","video/webm","video/quicktime","video/x-matroska"],image:phoneImageTypes,logo:phoneImageTypes,hero:phoneImageTypes,course_cover:phoneImageTypes,profile_image:phoneImageTypes,pdf:["application/pdf"],attachment:["application/pdf","image/jpeg","image/png","image/webp"] };
const labels:Record<Phase,string>={idle:"اسحب الملف هنا أو اضغط للاختيار",ready:"جاهز للرفع",uploading:"جاري الرفع",paused:"تم إيقاف الرفع مؤقتًا",processing:"جاري تجهيز الفيديو",success:"تم رفع الملف بنجاح",error:"فشل الرفع",cancelled:"تم إلغاء الرفع"};
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(2)} GB`}
function formatTime(seconds:number){if(!Number.isFinite(seconds)||seconds<0)return "—";const minutes=Math.floor(seconds/60);const rest=Math.round(seconds%60);return minutes?`${minutes} د ${rest} ث`:`${rest} ث`}
async function prepareImage(file:File,ratio:number|undefined,focal:number){let bitmap:ImageBitmap;try{bitmap=await createImageBitmap(file)}catch{throw new Error("تعذر قراءة الصورة. اختر JPEG أو PNG، أو اسمح للهاتف بتحويل صورة HEIC.")}let sx=0,sy=0,sw=bitmap.width,sh=bitmap.height;if(ratio){if(sw/sh>ratio){sw=sh*ratio;sx=(bitmap.width-sw)*(focal/100)}else{sh=sw/ratio;sy=(bitmap.height-sh)/2}}const outputRatio=ratio??sw/sh;const maxWidth=Math.min(1920,sw);const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(maxWidth));canvas.height=Math.max(1,Math.round(maxWidth/outputRatio));const context=canvas.getContext("2d");if(!context){bitmap.close();throw new Error("تعذر تجهيز الصورة")}context.drawImage(bitmap,sx,sy,sw,sh,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.9));if(!blob)throw new Error("تعذر تجهيز الصورة");const outputType=blob.type==="image/webp"||blob.type==="image/jpeg"||blob.type==="image/png"?blob.type:"image/png";const extension=outputType==="image/webp"?"webp":outputType==="image/jpeg"?"jpg":"png";return new File([blob],file.name.replace(/\.[^.]+$/,"")+"."+extension,{type:outputType})}
export function MediaUploader({resourceType,courseId,lessonId,acceptedMimeTypes,maximumFileSize,multiple=false,aspectRatio,onUploadComplete,onUploadError}:Props){const inputRef=useRef<HTMLInputElement>(null);const tusRef=useRef<tus.Upload|null>(null);const xhrRef=useRef<XMLHttpRequest|null>(null);const sampleRef=useRef({time:0,bytes:0});const[file,setFile]=useState<File|null>(null);const[phase,setPhase]=useState<Phase>("idle");const[progress,setProgress]=useState(0);const[speed,setSpeed]=useState(0);const[remaining,setRemaining]=useState(0);const[message,setMessage]=useState("");const[dragging,setDragging]=useState(false);const[focal,setFocal]=useState(50);const[preview,setPreview]=useState<string|null>(null);const mimes=acceptedMimeTypes??defaults[resourceType];const isVideo=resourceType==="video";const isImage=resourceType==="image"||resourceType==="logo"||resourceType==="hero"||resourceType==="course_cover"||resourceType==="profile_image";const ratio=aspectRatio??(resourceType==="logo"||resourceType==="profile_image"?1:resourceType==="hero"||resourceType==="course_cover"?16/9:undefined);const active=phase==="uploading"||phase==="paused"||phase==="processing";
useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(active){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[active]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
function choose(next:File|null){if(!next)return;if(!mimes.includes(next.type)){fail("نوع الملف غير مدعوم");return}if(maximumFileSize&&next.size>maximumFileSize){fail("حجم الملف أكبر من الحد المسموح");return}if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(isImage?URL.createObjectURL(next):null);setPhase("ready");setProgress(0);setMessage("")}
function fail(text:string){setPhase("error");setMessage(text);onUploadError?.(text)}function updateProgress(uploaded:number,total:number){const now=Date.now();const elapsed=(now-sampleRef.current.time)/1000;if(elapsed>=.5){const current=(uploaded-sampleRef.current.bytes)/elapsed;setSpeed(Math.max(0,current));setRemaining(current>0?(total-uploaded)/current:0);sampleRef.current={time:now,bytes:uploaded}}setProgress(total?Math.round(uploaded/total*100):0)}
async function start(){if(!file||active)return;setPhase("uploading");setMessage("");sampleRef.current={time:Date.now(),bytes:0};try{const prepared=isImage?await prepareImage(file,ratio,focal):file;if(isVideo)await startVideo(prepared);else startFile(prepared)}catch(error){fail(error instanceof Error?error.message:"تعذر بدء الرفع")}}
async function startVideo(uploadFile:File){const response=await fetch("/api/media/video/create-upload",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileName:uploadFile.name,mimeType:uploadFile.type,fileSize:uploadFile.size,resourceType,title:uploadFile.name.replace(/\.[^.]+$/,"") ,courseId,lessonId})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message??"تعذر تجهيز رفع الفيديو");const credentials=data.upload;const upload=new tus.Upload(uploadFile,{endpoint:credentials.endpoint,retryDelays:[0,3000,5000,10000,20000,60000],chunkSize:25*1024*1024,headers:{AuthorizationSignature:credentials.signature,AuthorizationExpire:String(credentials.expirationTime),VideoId:credentials.videoId,LibraryId:credentials.libraryId},metadata:{filetype:uploadFile.type,title:uploadFile.name},removeFingerprintOnSuccess:true,onProgress:updateProgress,onError:error=>fail(error.message||"انقطع رفع الفيديو"),onSuccess:async()=>{await fetch(`/api/media/video/${credentials.mediaId}`,{method:"PATCH"});setPhase("processing");setProgress(100);pollVideo(credentials.mediaId)}});tusRef.current=upload;const previous=await upload.findPreviousUploads();if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()}
function startFile(uploadFile:File){const body=new FormData();body.set("file",uploadFile);body.set("resourceType",resourceType);if(courseId)body.set("courseId",courseId);if(lessonId)body.set("lessonId",lessonId);const xhr=new XMLHttpRequest();xhrRef.current=xhr;xhr.open("POST","/api/media/file/upload");xhr.upload.onprogress=event=>{if(event.lengthComputable)updateProgress(event.loaded,event.total)};xhr.onerror=()=>fail("انقطع الاتصال أثناء رفع الملف");xhr.onabort=()=>setPhase("cancelled");xhr.onload=()=>{const data=JSON.parse(xhr.responseText||"null");if(xhr.status>=200&&xhr.status<300){setPhase("success");setProgress(100);onUploadComplete?.(data.asset)}else fail(data?.message??"فشل رفع الملف")};xhr.send(body)}
async function pollVideo(id:string){for(let attempt=0;attempt<120;attempt++){await new Promise(resolve=>setTimeout(resolve,5000));const response=await fetch(`/api/media/video/${id}`,{cache:"no-store"});const data=await response.json().catch(()=>null);if(!response.ok){fail(data?.message??"تعذر متابعة تجهيز الفيديو");return}setProgress(Number(data.asset.uploadProgress??100));if(data.asset.processingStatus==="READY"){setPhase("success");onUploadComplete?.(data.asset);return}if(data.asset.processingStatus==="FAILED"){fail(data.asset.errorMessage??"فشل تجهيز الفيديو");return}}fail("استغرق تجهيز الفيديو وقتًا أطول من المتوقع. يمكنك متابعته من مكتبة الوسائط.")}
async function pause(){if(tusRef.current&&phase==="uploading"){await tusRef.current.abort();setPhase("paused")}}function resume(){if(tusRef.current&&phase==="paused"){setPhase("uploading");tusRef.current.start()}}async function cancel(){if(tusRef.current)await tusRef.current.abort(true);xhrRef.current?.abort();setPhase("cancelled");setProgress(0)}function reset(){setFile(null);setPhase("idle");setProgress(0);setMessage("");setSpeed(0);setRemaining(0);if(preview)URL.revokeObjectURL(preview);setPreview(null)}
return <section className={`mediaUploader ${dragging?"isDragging":""} phase-${phase}`} dir="rtl"><input ref={inputRef} type="file" hidden accept={mimes.join(",")} multiple={multiple} onChange={event=>choose(event.target.files?.[0]??null)}/><div className="mediaDropzone" role="button" tabIndex={0} onClick={()=>!active&&inputRef.current?.click()} onKeyDown={event=>{if(event.key==="Enter")inputRef.current?.click()}} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);choose(event.dataTransfer.files?.[0]??null)}}>{preview?<img src={preview} alt="معاينة الملف" style={{objectPosition:`${focal}% 50%`,aspectRatio:ratio}}/>:<span className="mediaDropIcon"><UploadCloud size={30}/></span>}<div><b>{labels[phase]}</b><p>{file?file.name:"MP4، WebM، صور أو PDF حسب نوع الحقل"}</p>{file&&<small>{formatBytes(file.size)}</small>}</div></div>{isImage&&file&&ratio&&<label className="mediaFocal"><span>موضع الجزء المهم في الصورة</span><input type="range" min="0" max="100" value={focal} onChange={event=>setFocal(Number(event.target.value))}/></label>}{phase!=="idle"&&<div className="mediaUploadStatus"><div className="mediaProgress"><i style={{width:`${progress}%`}}/></div><div className="mediaStats"><span>{progress}%</span>{phase==="uploading"&&<><span>{formatBytes(speed)}/ث</span><span>متبقي {formatTime(remaining)}</span></>}</div>{message&&<p className="mediaError">{message}</p>}<div className="mediaActions">{phase==="ready"||phase==="error"?<button className="btn primary" onClick={start}>{phase==="error"?<RefreshCcw size={16}/>:<UploadCloud size={16}/>} {phase==="error"?"إعادة المحاولة":"ابدأ الرفع"}</button>:null}{isVideo&&phase==="uploading"?<button onClick={pause}><Pause size={16}/> إيقاف مؤقت</button>:null}{phase==="paused"?<button onClick={resume}><Play size={16}/> استكمال</button>:null}{active?<button className="danger" onClick={cancel}><X size={16}/> إلغاء</button>:null}{phase==="success"?<><span className="mediaSuccess"><CheckCircle2 size={17}/> الملف جاهز</span><button onClick={reset}>رفع ملف آخر</button></>:null}{phase==="cancelled"?<button onClick={reset}>اختيار ملف جديد</button>:null}</div></div>}</section>}
export const VideoUploader=(props:Omit<Props,"resourceType">)=><MediaUploader {...props} resourceType="video"/>;export const LogoUploader=(props:Omit<Props,"resourceType"|"aspectRatio">)=><MediaUploader {...props} resourceType="logo" aspectRatio={1}/>;export const HeroUploader=(props:Omit<Props,"resourceType"|"aspectRatio">)=><MediaUploader {...props} resourceType="hero" aspectRatio={16/9}/>;export const DocumentUploader=(props:Omit<Props,"resourceType">)=><MediaUploader {...props} resourceType="attachment"/>;