import {Brand,Top} from "./ui";
const courses=[["الأول الثانوي","أساسيات الكيمياء","افهم الذرة والجدول الدوري من الصفر.","Na","mint","32 درس"],["الثاني الثانوي","الكيمياء المتقدمة","الروابط والتفاعلات والحساب الكيميائي.","O₂","blue","41 درس"],["الثالث الثانوي","معسكر الثانوية العامة","شرح شامل وبنك أسئلة يحاكي الامتحان.","Fe","orange","68 درس"]];
const features=[["◉","شرح يثبت المعلومة","تبسيط بصري وتدريب بعد كل فكرة."],["✦","خطة مذاكرة ذكية","مهام يومية تتكيف مع مستواك."],["↗","تحليل نقاط الضعف","تقارير تقترح ما تحتاج لمراجعته."],["🏆","تحديات ومكافآت","نقاط وشارات تحافظ على حماسك."]];
export default function Home(){return <main><Top/>
<section className="hero"><div className="wrap heroGrid"><div className="heroCopy"><span className="tag">ــ منصتك الأولى في الكيمياء</span><h1>الكيمياء مش حفظ،<br/>الكيمياء <em>حكاية</em> هتفهمها.</h1><p>مع د. عبد الرحمن حسان، هتفهم كل فكرة من أصلها، وتتدرّب عليها لحد ما تبقى الكيمياء أسهل مادة عندك.</p><div className="heroBtns"><a className="btn primary" href="/dashboard">ابدأ رحلتك مجانًا ←</a><a className="watch" href="#why"><b>▶</b> شوف هنتعلم إزاي</a></div><div className="trust"><div><i>م</i><i>ي</i><i>ع</i><i>س</i></div><span><b>+12,500 طالب</b><small>بدأوا رحلتهم معانا</small></span><strong>★★★★★</strong></div></div>
<div className="visual"><div className="orbit one"/><div className="orbit two"/><div className="teacher"><div className="teacherTop"><b>د.ع</b><span><small>معاك خطوة بخطوة</small><strong>د. عبد الرحمن حسان</strong><em>مدرس الكيمياء</em></span><i>● مباشر</i></div><div className="screen"><div className="molecule"><i>H</i><b>O</b><i>H</i></div><a href="/course">▶</a><span>الدرس ٨<br/><b>الروابط الكيميائية</b></span></div><div className="progress"><span>تقدمك في الكورس <b>68%</b></span><i><b style={{width:"68%"}}/></i></div></div><div className="score">نتيجة آخر اختبار<b>18<small>/20</small></b><em>ممتاز! استمر 🔥</em></div><div className="streak"><b>🔥 14</b><span>يوم متواصل</span></div></div></div></section>
<section className="wrap stats" id="results">{[["+12.5K","طالب على المنصة"],["94%","إكمال الكورسات"],["+2.4M","سؤال تم حله"],["4.9/5","تقييم الطلاب"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
<section className="wrap section" id="courses"><div className="heading"><div><span className="tag orange">اختار مرحلتك</span><h2>منهج كامل. خطوة بخطوة.</h2></div><a href="/dashboard">عرض كل الكورسات ←</a></div><div className="courses">{courses.map(c=><a className="course" href="/course" key={c[1]}><div className={"art "+c[4]}><i/><i/><i/><b>{c[3]}</b><span>{c[0]}</span></div><div className="courseText"><small>{c[0]}</small><h3>{c[1]}</h3><p>{c[2]}</p><div>◷ {c[5]} <b>ابدأ الآن ←</b></div></div></a>)}</div></section>
<section className="why" id="why"><div className="wrap"><div className="center"><span className="tag orange">تجربة تعليم مختلفة</span><h2>كل اللي محتاجه عشان تتفوّق</h2><p>مش بس فيديوهات. نظام بيفهم مستواك ويمشي معاك لحد هدفك.</p></div><div className="features">{features.map(f=><article key={f[1]}><i>{f[0]}</i><h3>{f[1]}</h3><p>{f[2]}</p><a href="/dashboard">اكتشف الميزة ←</a></article>)}</div></div></section>
<section className="wrap section success"><div className="quote"><b>“</b><p>أول مرة أحس إن الكيمياء منطقية مش مجرد معادلات بنحفظها. طريقة الشرح والتدريب اليومي فرّقوا معايا جدًا.</p><div><i>س</i><span><strong>سارة أحمد</strong><small>الثالث الثانوي · دفعة 2025</small></span><em>98%</em></div></div><div><span className="tag orange">قصص نجاح حقيقية</span><h2>طلابنا مش أرقام.<br/>كل واحد فيهم قصة نجاح.</h2><p>من أول درس لحد لجنة الامتحان، بنفضل معاك بالمتابعة والتحليل والدعم.</p><div className="mini"><span><b>+340</b><small>طالب فوق 95%</small></span><span><b>27</b><small>من أوائل الجمهورية</small></span></div><a className="btn dark" href="/dashboard">ابدأ قصة نجاحك ←</a></div></section>
<section className="parentBand"><div className="wrap parentGrid"><div><span className="tag pale">لأن نجاحه يهمّك</span><h2>خليك مطمّن على مستواه،<br/>من غير ما تسأله كل يوم.</h2><p>لوحة لولي الأمر تعرض الحضور، المشاهدة، النتائج ونقاط الضعف لحظة بلحظة.</p><a className="btn white" href="/parents">استكشف لوحة ولي الأمر ←</a></div><div className="phone"><b>متابعة يوسف</b><div className="ring">84%<small>التزام</small></div><p><span>وقت المذاكرة</span><b>8س 24د</b></p><p><span>متوسط الاختبارات</span><b>91%</b></p><p><span>الواجبات</span><b>7 / 8</b></p></div></div></section>
<section className="wrap section" id="price"><div className="center"><span className="tag orange">اشتراك واضح وبسيط</span><h2>استثمر في درجتك من النهارده</h2></div><div className="pricing"><div><span>باقة الترم الكامل</span><h3>كل محتوى الصف + المتابعة الذكية</h3><ul><li>✓ شرح المنهج كاملًا</li><li>✓ بنك أسئلة وامتحانات</li><li>✓ تقارير ولي الأمر</li><li>✓ مراجعات ليلة الامتحان</li></ul></div><div><del>1,490 ج.م</del><b>990 <small>ج.م</small></b><p>دفعة واحدة · وصول حتى نهاية الترم</p><a className="btn primary" href="/dashboard">اشترك الآن ←</a></div></div></section>
<section className="wrap section faq"><div className="center"><span className="tag orange">أسئلة متكررة</span><h2>كل إجابة تحتاجها</h2></div>{[["هل أقدر أشاهد الدروس من الموبايل؟","نعم، وتتابع من حيث توقفت على أي جهاز."],["هل يوجد متابعة لولي الأمر؟","نعم، بتقارير الحضور والنتائج والواجبات."],["ماذا لو فاتني درس مباشر؟","تُضاف الإعادة والمرفقات إلى حسابك."]].map(x=><details key={x[0]}><summary>{x[0]} <b>+</b></summary><p>{x[1]}</p></details>)}</section>
<section className="cta"><div className="wrap"><div><span>جاهز تغيّر علاقتك بالكيمياء؟</span><h2>ابدأ أول درس مجانًا دلوقتي.</h2></div><a className="btn white" href="/dashboard">ابدأ مجانًا ←</a></div></section>
<footer><div className="wrap foot"><div><Brand/><p>منصة متكاملة تساعد طلاب الثانوية على فهم الكيمياء وتحقيق أفضل نتيجة.</p></div><div><b>المنصة</b><a href="#courses">الكورسات</a><a href="#price">الاشتراك</a><a href="/dashboard">لوحة الطالب</a></div><div><b>الدعم</b><a href="#faq">الأسئلة الشائعة</a><a href="mailto:support@example.com">تواصل معنا</a><a href="/parents">ولي الأمر</a></div></div><div className="wrap copy">© 2026 منصة د. عبد الرحمن حسان <span>صُنع بشغف لطلاب مصر 🇪🇬</span></div></footer></main>}