ALTER TABLE "TeacherBillingSettings"
  ADD COLUMN IF NOT EXISTS "openingFeeAmount" DECIMAL(10,2) NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS "openingFeeDueAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "openingFeeStatus" TEXT NOT NULL DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS "openingFeeActivatedAt" TIMESTAMP(3);

ALTER TABLE "TeacherBillingPaymentSubmission"
  ADD COLUMN IF NOT EXISTS "proofUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "purpose" TEXT NOT NULL DEFAULT 'MONTHLY';
