import { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";
import { authorizeSuperAdmin, isSameOrigin } from "@/lib/api-auth";
import { requestFingerprint } from "@/lib/auth";
import { notifySubscriptionApproved } from "@/lib/notifications/events";
import { prisma } from "@/lib/prisma";
import { addUtcMonths } from "@/lib/subscriptions";
const schema=z.object({tenantId:z.string().cuid(),monthlyPrice:z.number().positive().max(1_000_000),activeStudentLimit:z.number().int().positive().nullable(),storageLimitGb:z.number().int().positive().nullable(),durationMonths:z.number().int().min(1).max(36)});
export async function POST(request:Request){const auth=await authorizeSuperAdmin();if(!auth.ok)return auth.response;if(!isSameOrigin(request))return NextResponse.json({ok:false,message:"طلب غير صالح"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false,message:"راجع بيانات اشتراك Enterprise"},{status:400});const data=parsed.data;const now=new Date(),end=addUtcMonths(now,data.durationMonths),{ipHash}=await requestFingerprint();const result=await prisma.$transaction(async tx=>{await tx.$executeRaw(Prisma.sql`SELECT pg_advisory_xact_lock(hashtext(${data.tenantId}))`);const [subscription,plan,tenant]=await Promise.all([tx.tenantSubscription.findUnique({where:{tenantId:data.tenantId}}),tx.subscriptionPlan.findUnique({where:{code:"ENTERPRISE"}}),tx.tenant.findUnique({where:{id:data.tenantId},select:{id:true,name:true}})]);if(!subscription||!plan||!tenant)throw new Error("TENANT_NOT_FOUND");const updated=await tx.tenantSubscription.update({where:{id:subscription.id},data:{planId:plan.id,status:"ACTIVE",billingCycle:"CUSTOM",baseMonthlyPrice:data.monthlyPrice,billedAmount:data.monthlyPrice*data.durationMonths,discountPercent:0,activeStudentLimit:data.activeStudentLimit,storageLimitGb:data.storageLimitGb,currentPeriodStart:now,currentPeriodEnd:end,gracePeriodEndsAt:null,pendingPlanId:null,pendingDowngradeAt:null,version:{increment:1}}});await tx.tenant.update({where:{id:tenant.id},data:{status:"ACTIVE",suspendedAt:null}});await tx.subscriptionEvent.create({data:{tenantId:tenant.id,subscriptionId:subscription.id,actorUserId:auth.context.user.id,type:"ACTIVATED",key:`custom-enterprise:${subscription.id}:${now.toISOString()}`,payload:{monthlyPrice:data.monthlyPrice,durationMonths:data.durationMonths,activeStudentLimit:data.activeStudentLimit,storageLimitGb:data.storageLimitGb}}});await tx.auditLog.create({data:{tenantId:tenant.id,actorId:auth.context.user.id,action:"CUSTOM_ENTERPRISE_SUBSCRIPTION_ACTIVATED",entityType:"TenantSubscription",entityId:subscription.id,before:{status:subscription.status,planId:subscription.planId},after:{status:"ACTIVE",planId:plan.id,currentPeriodEnd:end,...data},ipHash}});return{updated,tenant}} ,{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await notifySubscriptionApproved({tenantId:data.tenantId,requestId:`custom-${result.updated.id}-${now.getTime()}`,planName:"Enterprise",periodEnd:end}).catch(()=>undefined);return NextResponse.json({ok:true,subscription:{id:result.updated.id,currentPeriodEnd:end}});}