-- Role values must be committed before the data migration can use them.
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEACHER_OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEACHER_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TEACHER_EDITOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SUPPORT_STAFF';
