ALTER TABLE "TenantSettings"
ADD COLUMN IF NOT EXISTS "supportedGrades" "Grade"[] NOT NULL DEFAULT ARRAY['FIRST_PREPARATORY'::"Grade", 'SECOND_PREPARATORY'::"Grade", 'THIRD_PREPARATORY'::"Grade", 'FIRST_SECONDARY'::"Grade", 'SECOND_SECONDARY'::"Grade", 'THIRD_SECONDARY'::"Grade"];
